config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "customer/registrations",
   sessions: 'customer/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }
  namespace :admin do
   resources :genres, only: [:index, :create, :edit, :update]
   resources :products, only: [:new, :index, :create, :show, :edit, :update]
   resources :orders, only: [:show, :update, :index] do
    member do
     get :customer_index
    end
   end
   resources :order_items, only: [:update]
   resources :customers, only: [:index, :show, :edit, :update]
  end
  scope module: "customer" do
   root to: 'products#top'
   get 'about' => 'products#about', as: 'about'
   #get "/sign_out" => "sessions#destroy" #要相談
   get "/customers/my_page" => "customers#show" #会員情報詳細ページ（マイページ）表示
   get "/customers/confirm" => "customers#confirm" #退会確認画面の表示
   patch "/customers/out" => "customers#out" #退会フラグを切り替える
   # post "/orders/confirm" => "orders#confirm" #注文情報確認画面を表示する
   resources :products, only: [:index,:show]
   resources :genres, only: [:show]
   resources :customers, only: [:edit,:update]
   resources :cart_items, only: [:index,:update,:destroy,:create] do
    collection do #:idをつけないように!!
     delete :destroy_all #カートを空にする
    end
   end
   resources :orders, only: [:index,:show,:new,:create] do
    collection do
     get :thanks
     post :confirm
    end
   end
   resources :addresses, only: [:index,:create,:destroy,:edit,:update]
  end
# ここまで↑↑ 会員
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    flash[:notice] = "顧客情報を更新しました。"
    redirect_to admin_customer_path(@customer)
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController
   before_action :authenticate_customer!

  def index
    @address = Address.new
    @addresses = current_customer.addresses
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      flash[:notice] = "配送先を登録しました。"
      redirect_to addresses_path
    else
      flash.now[:alert] = "配送先を入力してください。"
      @addresses = current_customer.addresses
      render 'index'
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      flash[:notice] = "配送先を更新しました。"
      redirect_to addresses_path
    else
      flash.now[:alert] = "配送先を入力してください。"
      render "edit"
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    flash[:notice] = "配送先を削除しました。"
    redirect_to request.referer
  end


  private

  def address_params
    params.require(:address).permit(:name, :postal_code, :address)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  def index
    @cart_items = current_customer.cart_items
    @cart_item = CartItem.new
    @total = @cart_items.inject(0){|sum, product| sum + product.subtotal}
  end

  def create
    if customer_signed_in?
      if CartItem.find_by(product_id: cart_item_params[:product_id])
        @cart_item = CartItem.find_by(product_id: cart_item_params[:product_id])
        @cart_item.product_count += (cart_item_params[:product_count]).to_i
      else
        @cart_item = CartItem.new(cart_item_params)
        @cart_item.customer_id = current_customer.id
      end
      if @cart_item.save
       redirect_to cart_items_path
      else
       redirect_to products_path
      end
    else
      redirect_to new_customer_session_path
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    @cart_items = current_customer.cart_items
    @total = @cart_items.inject(0){|sum, product| sum + product.subtotal}
  end

  def destroy
    @cart_item = CartItem.find(params[:id]).destroy
    @cart_items = current_customer.cart_items
    @total = @cart_items.inject(0){|sum, product| sum + product.subtotal}

    #redirect_to cart_items_path
  end

  def destroy_all
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    @total = @cart_items.inject(0){|sum, product| sum + product.subtotal}
    #redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:product_id, :product_count)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
  end

  def confirm
  end
  
  def out
    @customer = current_customer
    @customer.update(is_deleted: true)
    #論理削除
    reset_session
    flash[:notice] = "退会しました"
    redirect_to root_path
  end

  def edit
    @customer = current_customer
  end
  
  def update
    @customer = current_customer
    @customer.update(customer_params)
    flash[:notice] = "会員情報を更新しました。"
    redirect_to customers_my_page_path
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/customer/genres_controller.rb
class Customer::GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
    @genres = Genre.all
    @products = Product.where(genre_id: @genre.id, is_sales: true).page(params[:page])
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!

  def new
    @order = Order.new
  end

  def confirm
    @order_price = 0
    @cart_items = current_customer.cart_items
    @order_item = OrderItem.new
    @order = Order.new
    @order.payment_method = params[:order][:payment_method]
    if params[:order][:address_option] == "0" #自分の住所の場合
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_option] == "1" #登録済住所の場合
      if params[:order][:address_id] == ""
        flash.now[:alert] = "住所を選択して下さい。"
        render :new
      else
        @address = Address.find(params[:order][:address_id])
        @order.postal_code = @address.postal_code
        @order.address = @address.address
        @order.name = @address.name
      end
    elsif params[:order][:address_option] == "2" #新しいお届け先
      if params[:order][:postal_code] == "" || params[:order][:address] == "" || params[:order][:name] == ""
        flash.now[:alert] = "新しいお届け先を入力してください。"
        render :new
      else
        @order.postal_code = params[:order][:postal_code]
        @order.address = params[:order][:address]
        @order.name = params[:order][:name]
      end
    else
      flash.now[:alert] = "配送先を選択してください。"
      render :new
    end
  end

 def create
    @order = Order.new(order_params)
    @order.save
    @cart_items = current_customer.cart_items.all
    @cart_items.each do |cart_item|
      @order_item = OrderItem.new
      @order_item.order_id = @order.id
      @order_item.product_id = cart_item.product.id
      @order_item.product_count = cart_item.product_count
      @order_item.purchase_price = cart_item.product.with_tax_price
      @order_item.save
    end
    current_customer.cart_items.destroy_all
    redirect_to thanks_orders_path
 end

  def thanks
  end

  def index
    @orders = current_customer.orders.all.page(params[:page]).per(5).order(id: "DESC")
  end

  def show
    @order = current_customer.orders.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :total_price, :payment_method, :postal_code, :address, :name, :postage)
  end

end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  def top
    @products = Product.all.order(created_at: :desc).limit(4)
    @genres = Genre.all
  end

  def about
  end

  def index
    @products = Product.where(is_sales: true).page(params[:page])
    @genres = Genre.all
  end

  def show
    @product = Product.find(params[:id])
    @genres = Genre.all
    @cart_item = CartItem.new
  end

  private

  def cart_item_params
    params.require(:cart_items).permit(:product_id, :product_count)
  end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    customers_my_page_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  #before_action :reject_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  #余裕あれば確認
  # protected
  
  # def reject_customer
  #   @customer = Customer.find_by(email: params[:customer][:email])
  #     if @customer
  #       if (@customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted? == false))
  #         redirect_to new_customer_registration_path
  #       end
  #     end
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/adresses_helper.rb
module Customer::AdressesHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/genre_helper.rb
module Customer::GenreHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/customer/customers/confirm.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-10 mx-auto">
      <h1 class="mt-5"><strong>本当に退会しますか？</strong></h1>
      <div>
        <p>退会すると、会員登録情報や</p>
        <p>これまでの購入履歴が閲覧できなくなります。</p>
        <p>退会する場合は、「退会する」をクリックしてください。</p>
      </div>
    </div>
  </div>
  <div class="row justify-content-center mt-5 mb-5">
    <div class="col-3">
      <%= link_to "退会しない", customers_my_page_path, class: "btn btn-primary" %>
    </div>
    <div class="col-3">
      <%= link_to "退会する", customers_out_path, method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/customer/customers/edit.html.erb
<div class="container">
  <%= form_with model: @customer do |f| %>
    <div class="row">
      <h3 class="m-3 bg-light">会員情報編集</h3>
    </div>
    
    <div class="field row">
      <div class="col-2"><%= f.label :name, "氏名" %></div>
      <div class="col-6 form-inline">
        <%= f.text_field :last_name, class: "form-control mr-2 mb-2" %>
        <%= f.text_field :first_name, class: "form-control  mb-2" %>
      </div>
    </div>
  
    <div class="field row">
      <div class="col-2"><%= f.label :name_kana, "フリガナ" %></div>
      <div class="col-6 form-inline">
        <%= f.text_field :last_name_kana, class: "form-control mr-2 mb-2" %>
        <%= f.text_field :first_name_kana, class: "form-control  mb-2" %>
      </div>
    </div>
    
    <div class="field row">
      <div class="col-2"><%= f.label :postal_code, "郵便番号" %></div>
      <div class="col-6"><%= f.text_field :postal_code, class: "form-control mb-2" %></div>
    </div>
    
    <div class="field row">
      <div class="col-2"><%= f.label :address, "住所" %></div>
      <div class="col-6"><%= f.text_field :address, class: "form-control mb-2" %></div>
    </div>
    
    <div class="field row">
      <div class="col-2"><%= f.label :telephone_number, "電話番号" %></div>
      <div class="col-6"><%= f.text_field :telephone_number, class: "form-control mb-2" %></div>
    </div>
    
    <div class="field row">
      <div class="col-2"><%= f.label :email, "メールアドレス" %></div>
      <div class="col-6"><%= f.email_field :email, autocomplete: "email", class: "form-control mb-2" %></div>
    </div>
    
    <div class="row my-5">
      <div class="col-2"></div>
      <div class="col-6 form-inline">
        <div class="mr-5">
          <%= f.submit "編集内容を保存", class: "btn btn-success" %>
        </div>
        <div>
          <%= link_to "退会する", customers_confirm_path, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/customer/customers/show.html.erb
<div class="container">
  <div class="row">
    <h3 class="m-3 bg-light">マイページ</h3>
  </div>
  <div class="row my-2">
    <div class="mr-3"><h4>登録情報</h4></div>
    <div>
      <%= link_to "編集する", edit_customer_path(current_customer), class: "btn btn-success ml-3" %>
    </div>
  </div>
  <div class="row">
    <table class="table table-border">
      <tr>
        <td>氏名</td>
        <td><%= current_customer.last_name %> <%= current_customer.first_name %></td>
      </tr>
      <tr>
        <td>カナ</td>
        <td><%= current_customer.last_name_kana %> <%= current_customer.first_name_kana %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><%= current_customer.postal_code %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= current_customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= current_customer.telephone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= current_customer.email %></td>
      </tr>
    </table>
  </div>
    <div class="row my-3">
      <div class="mr-2 col-2"><h4>配送先</h4></div>
      <div>
        <%= link_to "一覧を見る", addresses_path, class: "btn btn-primary" %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="mr-2 col-2"><h4>注文履歴</h4></div>
      <div>
        <%= link_to "一覧を見る", orders_path, class: "btn btn-primary" %>
      </div>
    </div>
</div>