config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "customer/registrations",
   sessions: 'customer/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }
  namespace :admin do
   resources :genres, only: [:index, :create, :edit, :update]
   resources :products, only: [:new, :index, :create, :show, :edit, :update]
   resources :orders, only: [:show, :update, :index] do
    member do
     get :customer_index
    end
   end
   resources :order_items, only: [:update]
   resources :customers, only: [:index, :show, :edit, :update]
  end
  scope module: "customer" do
   root to: 'products#top'
   get 'about' => 'products#about', as: 'about'
   #get "/sign_out" => "sessions#destroy" #要相談
   get "/customers/my_page" => "customers#show" #会員情報詳細ページ（マイページ）表示
   get "/customers/confirm" => "customers#confirm" #退会確認画面の表示
   patch "/customers/out" => "customers#out" #退会フラグを切り替える
   # post "/orders/confirm" => "orders#confirm" #注文情報確認画面を表示する
   resources :products, only: [:index,:show]
   resources :genres, only: [:show]
   resources :customers, only: [:edit,:update]
   resources :cart_items, only: [:index,:update,:destroy,:create] do
    collection do #:idをつけないように!!
     delete :destroy_all #カートを空にする
    end
   end
   resources :orders, only: [:index,:show,:new,:create] do
    collection do
     get :thanks
     post :confirm
    end
   end
   resources :addresses, only: [:index,:create,:destroy,:edit,:update]
  end
# ここまで↑↑ 会員
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy

  validates :name, presence:true
  validates :postal_code, presence:true
  validates :address, presence:true

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: { waiting: 0, paid_up: 1, under_production: 2, preparing: 3, shipped: 4 }


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.page(params[:page]).per(8).order(id: "DESC")
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    # @order_item = OrderItem.find(params[:id])
   if @order.update(order_params)
     @message = "注文ステータスを更新しました。"
     if @order.order_status == "paid_up"
          @order_items.each do |order_item|
            order_item.product_status = "waiting_production"
            order_item.save
          end
     end
    # binding.irb
        # redirect_to admin_order_path(@order)
   else
      render :show
   end
  end

  def customer_index
    @customer = Customer.find(params[:id])
    @orders = @customer.orders.page(params[:page]).per(8).order(id: "DESC")
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!

  def new
    @order = Order.new
  end

  def confirm
    @order_price = 0
    @cart_items = current_customer.cart_items
    @order_item = OrderItem.new
    @order = Order.new
    @order.payment_method = params[:order][:payment_method]
    if params[:order][:address_option] == "0" #自分の住所の場合
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_option] == "1" #登録済住所の場合
      if params[:order][:address_id] == ""
        flash.now[:alert] = "住所を選択して下さい。"
        render :new
      else
        @address = Address.find(params[:order][:address_id])
        @order.postal_code = @address.postal_code
        @order.address = @address.address
        @order.name = @address.name
      end
    elsif params[:order][:address_option] == "2" #新しいお届け先
      if params[:order][:postal_code] == "" || params[:order][:address] == "" || params[:order][:name] == ""
        flash.now[:alert] = "新しいお届け先を入力してください。"
        render :new
      else
        @order.postal_code = params[:order][:postal_code]
        @order.address = params[:order][:address]
        @order.name = params[:order][:name]
      end
    else
      flash.now[:alert] = "配送先を選択してください。"
      render :new
    end
  end

 def create
    @order = Order.new(order_params)
    @order.save
    @cart_items = current_customer.cart_items.all
    @cart_items.each do |cart_item|
      @order_item = OrderItem.new
      @order_item.order_id = @order.id
      @order_item.product_id = cart_item.product.id
      @order_item.product_count = cart_item.product_count
      @order_item.purchase_price = cart_item.product.with_tax_price
      @order_item.save
    end
    current_customer.cart_items.destroy_all
    redirect_to thanks_orders_path
 end

  def thanks
  end

  def index
    @orders = current_customer.orders.all.page(params[:page]).per(5).order(id: "DESC")
  end

  def show
    @order = current_customer.orders.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :total_price, :payment_method, :postal_code, :address, :name, :postage)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/_order_status.html.erb
<%= form_with model: order, url: admin_order_path(order), method: :patch, local: false  do |f| %>
  <%= f.select(:order_status, Order.order_statuses_i18n.invert, {selected: order.order_status}) %>
  <%= f.submit "更新", class: "btn btn-success" %>
<% end %>

app/views/admin/orders/customer_index.erb
<div class="container">
  <div class="row">
    <h3 class="bg-light my-5"><strong><%= @customer.last_name %><%= @customer.first_name %></strong>さんの<strong>注文履歴</strong></h3>
  </div>

  <div class="row">
    <table class="table">
      <thead>
        <tr  class="bg-light">
          <th>購入日時</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
       <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.created_at.strftime("%Y-%m-%d %H:%M:%S") ,admin_order_path(order) %></td>
          <td><%= order.order_items.sum(:product_count) %></td>
          <td><%= order.order_status_i18n %></td>
        </tr>
       <% end %>
      </tbody>
    </table>
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="bg-light my-5">注文履歴一覧</h3>
  </div>

  <div class="row">
    <table class="table">
      <thead>
        <tr  class="bg-light">
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
       <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.created_at.strftime("%Y-%m-%d %H:%M:%S") ,admin_order_path(order) %></td>
          <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
          <td><%= order.order_items.sum(:product_count) %></td>
          <td><%= order.order_status_i18n %></td>
        </tr>
       <% end %>
      </tbody>
    </table>
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <span id="flash"></span> <!-- TODO: Flash message for jQuery -->
  <div class="row">
    <div class="col-3">
      <h5 class="text-center mt-5">注文履歴の詳細</h5>
    </div>
     <div class="col-12 mt-3">
       <table class="col-6">
         <tr>
           <th>購入者</th>
           <td>
             <%= link_to admin_customer_path(@order.customer), class: "text-dark" do %>
               <%= @order.customer.last_name %><%= @order.customer.first_name %>
             <% end %>
           </td>
         </tr>
         <tr>
           <th>注文日</th>
           <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
         </tr>
         <tr>
           <th>配送先</th>
           <td>
             〒<%= @order.postal_code %>
             <%= @order.address %>
           </td>
         </tr>
         <tr>
           <th>宛名</th>
           <td>
             <%= @order.name %>
           </td>
         </tr>
         <tr>
           <th>支払方法</th>
           <td><%= @order.payment_method_i18n %></td>
         </tr>
         <tr>
           <th>注文ステータス</th>
           <td class="order_status_select">
             <%= render "order_status", order: @order %>
             <%#= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
               <%#= f.select(:order_status, Order.order_statuses_i18n.invert, {selected: @order.order_status}) %>
               <%#= f.submit "更新", class: "btn btn-success" %>
             <%# end %>
           </td>
         </tr>
       </table>
     </div>
  </div>

  <div class="row mt-4">
    <div class="col-8">
      <table class="table">
        <thead class="table-active">
          <tr class="bg-light">
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_items.each do |order_item| %>
            <tr id="order_item_<%= order_item.id %>">
              <td><%= order_item.product.name %></td>
              <td><%= order_item.product.with_tax_price.to_s(:delimited) %></td>
              <td><%= order_item.product_count %></td>
              <td><%= order_item.subtotal.to_s(:delimited) %></td>
              <td class="product_status_select">
                <%= render "admin/order_items/product_status", order: @order, order_item: order_item %>
              </td>
              <!--<%#= form_with(model:[@order, order_item], url: admin_order_item_path(order_id: @order.id, id: order_item.id), method: :patch, local: true) do |f| %>-->
              <!--  <td>-->
              <!--    <%#= f.select(:product_status, OrderItem.product_statuses_i18n.invert, {selected: order_item.product_status}) %>-->
              <!--    <%#= f.submit "更新", class: "btn btn-success" %>-->
              <!--  </td>-->
              <!--<%# end %>-->
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-4">
      <table class="col-7 mt-auto offset-1">
        <tr>
          <td>商品合計</td>
          <td class="text-right"><%= (@order.total_price - @order.postage).to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <td>送料</td>
          <td class="text-right"><%= @order.postage.to_s %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          　<td class="text-right"><strong><%= @order.total_price.to_s(:delimited) %>円</strong></td>
        </tr>
      </table>
    </div>
 </div>

</div>

app/views/admin/orders/update.js.erb
$(".order_status_select").html("<%= j(render 'admin/orders/order_status', order: @order) %>");
<% @order_items.each do |order_item| %>
  $("#order_item_<%= order_item.id %> .product_status_select").html("<%= j(render 'admin/order_items/product_status', order: @order, order_item: order_item) %>");
<% end %>
$('#flash').html('<strong><%= @message %></strong>')